2014-06-15 11:43:50,500 - [INFO] - from play in pool-4-thread-4 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-06-15 11:44:03,076 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:44:04,930 - [ERROR] - from application in New I/O worker #1 


! @6ih373f9f - Internal server error, for (GET) [/users] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10.jar:2.2.3]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 11:45:32,329 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:45:32,908 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-06-15 11:46:34,037 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:46:34,617 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-06-15 11:47:05,924 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:47:06,540 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:48:12,956 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:48:13,549 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:48:59,589 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:49:00,155 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:50:19,992 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:50:20,519 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:51:21,228 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:51:21,789 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:54:23,962 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:54:24,530 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:54:39,805 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 11:54:40,384 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 11:58:37,049 - [ERROR] - from application in New I/O worker #1 


! @6ih3915dp - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[value active is not a member of controllers.ReverseUsers]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 12:00:23,326 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 12:00:24,039 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 12:03:13,927 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 12:03:14,464 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 12:04:28,145 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 12:04:28,761 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 12:17:01,611 - [ERROR] - from application in New I/O worker #2 


! @6ih3bc1d4 - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 12:18:26,758 - [ERROR] - from application in New I/O worker #2 


! @6ih3bgnc1 - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:26:57,475 - [ERROR] - from application in New I/O worker #5 


! @6ih3kgkae - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: incompatible types: String cannot be converted to boolean]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:27:33,884 - [ERROR] - from application in New I/O worker #5 


! @6ih3kim6n - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:28:10,302 - [ERROR] - from application in New I/O worker #5 


! @6ih3kko3f - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:28:34,728 - [ERROR] - from application in New I/O worker #5 


! @6ih3km872 - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:34:24,397 - [ERROR] - from application in New I/O worker #2 


! @6ih3lg5dk - Internal server error, for (GET) [/users] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-15 13:34:52,477 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:34:54,915 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-06-15 13:36:48,233 - [INFO] - from play in play-internal-execution-context-7 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:36:48,776 - [INFO] - from play in play-internal-execution-context-7 
Application started (Dev)

2014-06-15 13:38:00,924 - [INFO] - from play in play-internal-execution-context-10 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:38:01,503 - [INFO] - from play in play-internal-execution-context-10 
Application started (Dev)

2014-06-15 13:38:58,922 - [INFO] - from play in play-internal-execution-context-15 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:38:59,523 - [INFO] - from play in play-internal-execution-context-15 
Application started (Dev)

2014-06-15 13:40:12,046 - [INFO] - from play in play-internal-execution-context-15 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:40:12,587 - [INFO] - from play in play-internal-execution-context-15 
Application started (Dev)

2014-06-15 13:41:59,444 - [ERROR] - from play in play-internal-execution-context-23 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 



2014-06-15 13:42:00,035 - [ERROR] - from application in play-internal-execution-context-23 


! @6ih3mg34e - Internal server error, for (GET) [/matches?s=team.name] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.matches.list$.apply(list.template.scala:99) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:163) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 23 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-15 13:42:02,823 - [ERROR] - from play in play-internal-execution-context-23 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 



2014-06-15 13:42:02,847 - [ERROR] - from application in play-internal-execution-context-23 


! @6ih3mg7i9 - Internal server error, for (GET) [/matches?s=position] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.matches.list$.apply(list.template.scala:99) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:163) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 23 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "POSITION" nie istnieje
Column "POSITION" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by position 
limit 11 [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-15 13:42:04,780 - [ERROR] - from play in play-internal-execution-context-23 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 



2014-06-15 13:42:04,795 - [ERROR] - from application in play-internal-execution-context-23 


! @6ih3mgaf8 - Internal server error, for (GET) [/matches?s=number] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.matches.list$.apply(list.template.scala:99) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:163) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 23 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "NUMBER" nie istnieje
Column "NUMBER" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by number 
limit 11 [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-15 13:42:07,421 - [ERROR] - from play in play-internal-execution-context-20 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 



2014-06-15 13:42:07,466 - [ERROR] - from application in play-internal-execution-context-20 


! @6ih3mgecn - Internal server error, for (GET) [/matches?s=team.name] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.matches.list$.apply(list.template.scala:99) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:163) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(routes_routing.scala:357) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 23 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-15 13:43:42,722 - [INFO] - from play in play-internal-execution-context-24 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:43:43,254 - [INFO] - from play in play-internal-execution-context-24 
Application started (Dev)

2014-06-15 13:44:26,490 - [INFO] - from play in play-internal-execution-context-24 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:44:27,132 - [INFO] - from play in play-internal-execution-context-24 
Application started (Dev)

2014-06-15 13:45:47,771 - [ERROR] - from play in play-internal-execution-context-28 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 



2014-06-15 13:45:47,787 - [ERROR] - from application in play-internal-execution-context-28 


! @6ih3n32bo - Internal server error, for (GET) [/games?s=season.year_start%2Fseason.year_end] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.games.list$.apply(list.template.scala:103) ~[na:na]
	at views.html.games.list$.render(list.template.scala:152) ~[na:na]
	at views.html.games.list.render(list.template.scala) ~[na:na]
	at controllers.Games.list(Games.java:22) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:397) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:397) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.mvc.Security$AuthenticatedAction.call(Security.java:45) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 24 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Cecha nie jest wspierana: "TIMESTAMP / TIMESTAMP"
Feature not supported: "TIMESTAMP / TIMESTAMP"; SQL statement:
select t0.id c0, t0.name c1, t0.season_id c2 from game t0 left outer join season t1 on t1.id = t0.season_id  where lower(t0.name) like ?  order by t1.year_start/t1.year_end 
limit 11 [50100-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.getUnsupportedException(DbException.java:204) ~[h2.jar:1.3.172]
	at org.h2.expression.Operation.optimize(Operation.java:306) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-15 13:46:20,186 - [INFO] - from play in play-internal-execution-context-30 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:46:20,733 - [INFO] - from play in play-internal-execution-context-30 
Application started (Dev)

2014-06-15 13:46:55,725 - [INFO] - from play in play-internal-execution-context-32 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:46:56,403 - [INFO] - from play in play-internal-execution-context-32 
Application started (Dev)

2014-06-15 13:48:22,665 - [INFO] - from play in play-internal-execution-context-34 
database [default] connected at jdbc:h2:mem:play

2014-06-15 13:48:23,258 - [INFO] - from play in play-internal-execution-context-34 
Application started (Dev)

