2014-06-14 19:04:10,080 - [INFO] - from play in pool-4-thread-3 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-06-14 19:04:16,209 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:04:17,346 - [ERROR] - from application in New I/O worker #1 


! @6igo5me9p - Internal server error, for (GET) [/] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10.jar:2.2.3]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:04:21,657 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:04:22,505 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-06-14 19:06:08,830 - [ERROR] - from application in New I/O worker #3 


! @6igo62n80 - Internal server error, for (GET) [/matches?s=team1] ->

play.PlayExceptions$CompilationException: Compilation error[value options is not a member of object models.Referee]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:07:45,276 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:07:46,219 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:07:57,068 - [ERROR] - from play in play-internal-execution-context-5 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NAME" nie istnieje
Column "NAME" not found; SQL statement:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name 



2014-06-14 19:07:57,092 - [ERROR] - from application in play-internal-execution-context-5 


! @6igo691bn - Internal server error, for (GET) [/matches/5] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Kolumna "NAME" nie istnieje
Column "NAME" not found; SQL statement:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "NAME" nie istnieje
Column "NAME" not found; SQL statement:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:885) ~[avaje-ebeanorm.jar:na]
	at models.Referee.options(Referee.java:51) ~[na:na]
	at views.html.matches.editForm$$anonfun$apply$1.apply(editForm.template.scala:75) ~[na:na]
	at views.html.matches.editForm$$anonfun$apply$1.apply(editForm.template.scala:45) ~[na:na]
	at views.html.helper.form$.apply(form.template.scala:45) ~[play_2.10.jar:2.2.3]
	at views.html.matches.editForm$.apply(editForm.template.scala:45) ~[na:na]
	at views.html.matches.editForm$.render(editForm.template.scala:102) ~[na:na]
	at views.html.matches.editForm.render(editForm.template.scala) ~[na:na]
	at controllers.Matches.edit(Matches.java:40) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(routes_routing.scala:509) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(routes_routing.scala:509) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "NAME" nie istnieje
Column "NAME" not found; SQL statement:
select t0.id c0, t0.lastname c1, t0.firstname c2, t0.city c3 from referee t0 order by name [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 31 common frames omitted

2014-06-14 19:08:16,378 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:08:16,977 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:09:39,997 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:09:40,583 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:19:13,273 - [ERROR] - from application in New I/O worker #8 


! @6igo7ldin - Internal server error, for (GET) [/matches?s=team1] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:25:35,935 - [ERROR] - from application in New I/O worker #2 


! @6igo8h7ki - Internal server error, for (GET) [/matches?s=team1] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:25:57,824 - [ERROR] - from application in New I/O worker #2 


! @6igo8ie4f - Internal server error, for (GET) [/matches?s=team1] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:29:20,061 - [ERROR] - from application in New I/O worker #2 


! @6igo9418m - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: class, interface, or enum expected]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:29:21,328 - [ERROR] - from application in New I/O worker #5 


! @6igo9435g - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: class, interface, or enum expected]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:29:53,970 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:29:54,515 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:30:38,147 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:30:38,680 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:33:17,802 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:33:18,450 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-06-14 19:46:42,777 - [ERROR] - from application in New I/O worker #7 


! @6igobb9l9 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[value User is not a member of object controllers.routes]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 19:47:04,214 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:47:04,846 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:48:07,421 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:48:08,689 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:49:06,117 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:49:06,751 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:49:20,370 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:49:20,899 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:49:51,281 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:49:51,807 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:50:09,623 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:50:10,335 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:50:30,544 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:50:31,116 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-06-14 19:50:44,057 - [INFO] - from play in play-internal-execution-context-26 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:50:44,644 - [INFO] - from play in play-internal-execution-context-26 
Application started (Dev)

2014-06-14 19:56:16,967 - [INFO] - from play in play-internal-execution-context-28 
database [default] connected at jdbc:h2:mem:play

2014-06-14 19:56:17,527 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2014-06-14 20:00:01,726 - [INFO] - from play in play-internal-execution-context-28 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:00:02,248 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2014-06-14 20:00:39,239 - [INFO] - from play in play-internal-execution-context-28 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:00:39,813 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2014-06-14 20:21:21,725 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:21:22,288 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:22:01,461 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:22:02,088 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:22:59,468 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:23:00,035 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:25:21,871 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:25:22,411 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:34:51,212 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:34:51,990 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:35:14,664 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:35:15,185 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:35:15,233 - [ERROR] - from play in play-internal-execution-context-42 
Cannot invoke the action, eventually got an error: java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5{0,number,integer} mecze|5<{0,number,integer} meczów

2014-06-14 20:35:15,541 - [ERROR] - from application in play-internal-execution-context-42 


! @6igohl2e7 - Internal server error, for (GET) [/matches?f=] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5{0,number,integer} mecze|5<{0,number,integer} meczów]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5{0,number,integer} mecze|5<{0,number,integer} meczów
	at java.text.MessageFormat.makeFormat(Unknown Source) ~[na:1.8.0_05]
	at java.text.MessageFormat.applyPattern(Unknown Source) ~[na:1.8.0_05]
	at java.text.MessageFormat.<init>(Unknown Source) ~[na:1.8.0_05]
	at play.api.i18n.MessagesApi$$anonfun$translate$1.apply(Messages.scala:256) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.MessagesApi$$anonfun$translate$1.apply(Messages.scala:255) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.api.i18n.MessagesApi.translate(Messages.scala:255) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8$$anonfun$apply$9.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8$$anonfun$apply$9.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.api.i18n.Messages$$anonfun$apply$8.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8.apply(Messages.scala:140) ~[play_2.10.jar:2.2.3]
	at scala.Option.flatMap(Option.scala:170) [scala-library.jar:na]
	at play.api.i18n.Messages$.apply(Messages.scala:140) ~[play_2.10.jar:2.2.3]
	at views.html.matches.list$.apply(list.template.scala:66) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:162) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.text.ChoiceFormat.applyPattern(Unknown Source) ~[na:1.8.0_05]
	at java.text.ChoiceFormat.<init>(Unknown Source) ~[na:1.8.0_05]
	... 37 common frames omitted

2014-06-14 20:36:24,462 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:36:24,985 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:36:25,031 - [ERROR] - from play in play-internal-execution-context-42 
Cannot invoke the action, eventually got an error: java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5#{0,number,integer} mecze|5<{0,number,integer} meczów

2014-06-14 20:36:25,037 - [ERROR] - from application in play-internal-execution-context-42 


! @6igohp1bi - Internal server error, for (GET) [/matches?f=] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5#{0,number,integer} mecze|5<{0,number,integer} meczów]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#0 meczów|1#1 mecz|<5#{0,number,integer} mecze|5<{0,number,integer} meczów
	at java.text.MessageFormat.makeFormat(Unknown Source) ~[na:1.8.0_05]
	at java.text.MessageFormat.applyPattern(Unknown Source) ~[na:1.8.0_05]
	at java.text.MessageFormat.<init>(Unknown Source) ~[na:1.8.0_05]
	at play.api.i18n.MessagesApi$$anonfun$translate$1.apply(Messages.scala:256) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.MessagesApi$$anonfun$translate$1.apply(Messages.scala:255) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.api.i18n.MessagesApi.translate(Messages.scala:255) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8$$anonfun$apply$9.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8$$anonfun$apply$9.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.api.i18n.Messages$$anonfun$apply$8.apply(Messages.scala:141) ~[play_2.10.jar:2.2.3]
	at play.api.i18n.Messages$$anonfun$apply$8.apply(Messages.scala:140) ~[play_2.10.jar:2.2.3]
	at scala.Option.flatMap(Option.scala:170) [scala-library.jar:na]
	at play.api.i18n.Messages$.apply(Messages.scala:140) ~[play_2.10.jar:2.2.3]
	at views.html.matches.list$.apply(list.template.scala:66) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:162) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.text.ChoiceFormat.applyPattern(Unknown Source) ~[na:1.8.0_05]
	at java.text.ChoiceFormat.<init>(Unknown Source) ~[na:1.8.0_05]
	... 37 common frames omitted

2014-06-14 20:37:58,598 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:37:59,148 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:38:20,747 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:38:21,368 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:44:30,218 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:44:30,813 - [ERROR] - from application in New I/O worker #6 


! @6igoj0i0i - Internal server error, for (GET) [/login] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10.jar:2.2.3]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10.jar:2.2.3]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 20:44:33,524 - [ERROR] - from play in New I/O worker #6 
Referential integrity constraint violation: "FK_MATCH_GAME_3: PUBLIC.MATCH FOREIGN KEY(GAME_ID) REFERENCES PUBLIC.GAME(ID) (1)"; SQL statement:
delete from game [23503-172] [ERROR:23503, SQLSTATE:23503]

2014-06-14 20:44:33,548 - [ERROR] - from application in New I/O worker #6 


! @6igoj0m1l - Internal server error, for (GET) [/@evolutions/apply/default?redirect=http%3A%2F%2Flocalhost%3A9000%2Flogin] ->

play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:193) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:277) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin.handleWebCommand(Evolutions.scala:560) ~[play-jdbc_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:175) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:174) ~[play_2.10.jar:2.2.3]
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foldLeft(List.scala:84) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:174) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at scala.Option.flatMap(Option.scala:170) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at scala.Option.orElse(Option.scala:257) ~[scala-library.jar:na]
	at play.core.ReloadableApplication.handleWebCommand(ApplicationProvider.scala:171) ~[play_2.10.jar:2.2.3]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch.apply(Exception.scala:102) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch.either(Exception.scala:124) ~[scala-library.jar:na]
	at play.core.server.Server$class.getHandlerFor(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:35) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9.apply(PlayDefaultUpstreamHandler.scala:118) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9.apply(PlayDefaultUpstreamHandler.scala:118) [play_2.10.jar:2.2.3]
	at scala.util.Either.fold(Either.scala:98) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:112) [play_2.10.jar:2.2.3]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

2014-06-14 20:44:35,233 - [ERROR] - from play in New I/O worker #6 
Naruszenie ograniczenia Klucza Glownego lub Indeksu Unikalnego: "PRIMARY_KEY_91 ON PUBLIC.SEASON(ID)"
Unique index or primary key violation: "PRIMARY_KEY_91 ON PUBLIC.SEASON(ID)"; SQL statement:
insert into season(id,year_start, year_end) values (1, '2013-01-01', '2014-01-01') [23505-172] [ERROR:23505, SQLSTATE:23505]

2014-06-14 20:44:35,237 - [ERROR] - from application in New I/O worker #6 


! @6igoj0ofd - Internal server error, for (GET) [/@evolutions/apply/default?redirect=http%3A%2F%2Flocalhost%3A9000%2Flogin] ->

play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:193) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:277) ~[play-jdbc_2.10.jar:2.2.3]
	at play.api.db.evolutions.EvolutionsPlugin.handleWebCommand(Evolutions.scala:560) ~[play-jdbc_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:175) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:174) ~[play_2.10.jar:2.2.3]
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foldLeft(List.scala:84) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:174) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at scala.Option.flatMap(Option.scala:170) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:173) ~[play_2.10.jar:2.2.3]
	at scala.Option.orElse(Option.scala:257) ~[scala-library.jar:na]
	at play.core.ReloadableApplication.handleWebCommand(ApplicationProvider.scala:171) ~[play_2.10.jar:2.2.3]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch.apply(Exception.scala:102) ~[scala-library.jar:na]
	at scala.util.control.Exception$Catch.either(Exception.scala:124) ~[scala-library.jar:na]
	at play.core.server.Server$class.getHandlerFor(Server.scala:79) ~[play_2.10.jar:2.2.3]
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:35) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9.apply(PlayDefaultUpstreamHandler.scala:118) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9.apply(PlayDefaultUpstreamHandler.scala:118) [play_2.10.jar:2.2.3]
	at scala.util.Either.fold(Either.scala:98) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:112) [play_2.10.jar:2.2.3]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) [netty.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

2014-06-14 20:44:37,821 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:44:38,342 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:45:34,911 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:45:35,437 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:46:20,532 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:46:21,217 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:46:39,700 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:46:40,247 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:49:03,487 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:49:04,121 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:51:03,846 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:51:04,393 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:52:18,516 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:52:19,190 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:53:11,816 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:53:12,544 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:54:16,560 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:54:17,114 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:55:01,118 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:55:01,678 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:56:07,950 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:56:08,486 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 20:59:49,815 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 20:59:50,356 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 21:01:04,370 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:01:04,894 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 21:03:45,833 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:03:46,421 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 21:04:10,729 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:04:11,264 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2014-06-14 21:04:39,657 - [INFO] - from play in play-internal-execution-context-61 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:04:40,209 - [INFO] - from play in play-internal-execution-context-61 
Application started (Dev)

2014-06-14 21:05:42,364 - [INFO] - from play in play-internal-execution-context-61 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:05:42,918 - [INFO] - from play in play-internal-execution-context-61 
Application started (Dev)

2014-06-14 21:07:27,969 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:07:28,565 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:08:03,761 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:08:04,335 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:08:25,282 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:08:25,828 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:08:47,977 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:08:48,586 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:09:14,643 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:09:15,200 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:10:24,379 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:10:24,926 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:11:38,675 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:11:39,241 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:11:52,935 - [INFO] - from play in play-internal-execution-context-63 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:11:53,500 - [INFO] - from play in play-internal-execution-context-63 
Application started (Dev)

2014-06-14 21:13:02,352 - [INFO] - from play in play-internal-execution-context-67 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:13:02,923 - [INFO] - from play in play-internal-execution-context-67 
Application started (Dev)

2014-06-14 21:14:10,923 - [INFO] - from play in play-internal-execution-context-67 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:14:11,466 - [INFO] - from play in play-internal-execution-context-67 
Application started (Dev)

2014-06-14 21:15:16,045 - [ERROR] - from application in New I/O worker #6 


! @6igon1hhk - Internal server error, for (GET) [/users/new] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : String("login")
 required: play.api.mvc.Call]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-06-14 21:15:29,800 - [INFO] - from play in play-internal-execution-context-68 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:15:30,346 - [INFO] - from play in play-internal-execution-context-68 
Application started (Dev)

2014-06-14 21:16:28,801 - [INFO] - from play in play-internal-execution-context-68 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:16:29,328 - [INFO] - from play in play-internal-execution-context-68 
Application started (Dev)

2014-06-14 21:16:54,230 - [INFO] - from play in play-internal-execution-context-69 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:16:54,772 - [INFO] - from play in play-internal-execution-context-69 
Application started (Dev)

2014-06-14 21:17:48,542 - [INFO] - from play in play-internal-execution-context-69 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:17:49,089 - [INFO] - from play in play-internal-execution-context-69 
Application started (Dev)

2014-06-14 21:18:39,652 - [ERROR] - from play in play-internal-execution-context-72 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 



2014-06-14 21:18:39,683 - [ERROR] - from application in play-internal-execution-context-72 


! @6igond6no - Internal server error, for (GET) [/matches?s=team.name] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:64) ~[avaje-ebeanorm.jar:na]
	at views.html.matches.list$.apply(list.template.scala:99) ~[na:na]
	at views.html.matches.list$.render(list.template.scala:163) ~[na:na]
	at views.html.matches.list.render(list.template.scala) ~[na:na]
	at controllers.Matches.list(Matches.java:28) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$11$$anonfun$apply$11.apply(routes_routing.scala:341) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at java.util.concurrent.FutureTask.report(Unknown Source) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.query.BaseFuture.get(BaseFuture.java:29) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getList(LimitOffsetPage.java:62) ~[avaje-ebeanorm.jar:na]
	... 23 common frames omitted
javax.persistence.PersistenceException: Query threw SQLException:Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:27) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CallableQueryList.call(CallableQueryList.java:15) ~[avaje-ebeanorm.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_05]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.doTheWork(PooledThread.java:156) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:123) ~[avaje-ebeanorm.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_05]
Caused by: org.h2.jdbc.JdbcSQLException: Kolumna "TEAM.NAME" nie istnieje
Column "TEAM.NAME" not found; SQL statement:
select t0.id c0, t0.queue c1, t0.score1 c2, t0.score2 c3, t0.score1_half c4, t0.score2_half c5, t0.status c6, t0.match_date c7, t0.weather c8, t0.viewers c9, t0.game_id c10, t0.statistics_id c11, t0.referee_id c12, t0.team1_id c13, t0.team2_id c14 from match t0 where lower(t0.weather) like ?  order by team.name 
limit 11 [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
	at org.h2.command.dml.Select.prepare(Select.java:808) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:219) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 9 common frames omitted

2014-06-14 21:19:34,644 - [INFO] - from play in play-internal-execution-context-72 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:19:35,208 - [INFO] - from play in play-internal-execution-context-72 
Application started (Dev)

2014-06-14 21:20:47,983 - [INFO] - from play in play-internal-execution-context-78 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:20:48,530 - [INFO] - from play in play-internal-execution-context-78 
Application started (Dev)

2014-06-14 21:21:51,567 - [INFO] - from play in play-internal-execution-context-81 
database [default] connected at jdbc:h2:mem:play

2014-06-14 21:21:52,125 - [INFO] - from play in play-internal-execution-context-81 
Application started (Dev)

